CREATE TABLE IF NOT EXISTS files (
    id SERIAL PRIMARY KEY,
    original_file_uri VARCHAR(255) NOT NULL,
    compressed_file_uri VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)

CREATE INDEX IF NOT EXISTS idx_files_id_hash ON files USING HASH (id);